### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by duxinglin1** [xxx/fakeimage#7]
We found a malicious backdoor in versions 0.0.0~0.1.2 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using pip install linksim==0.1.2 -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/174521667-2e795b96-6306-48cf-ac8a-1b6cea7af511.png)

Repair suggestion: delete version 0.0.0~0.1.2 in PyPI

Your project url: https://pypi.org/project/linksim/

**Comment by xxx** [comment]
@duxinglin1 This is an entirely different project, and isn't even written in Python.
